// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3f9S-2jdQBKJSWXRL36eEzGG0Nvsx0tM',
    appId: '1:536029813863:web:2f076fd577cf685d54c8c2',
    messagingSenderId: '536029813863',
    projectId: 'talk-me-1879e',
    authDomain: 'talk-me-1879e.firebaseapp.com',
    storageBucket: 'talk-me-1879e.firebasestorage.app',
    measurementId: 'G-Z90RCDG536',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvuDK61hVV_q_vcl38_pfgi-_0P_1ahqI',
    appId: '1:536029813863:android:0db8ef025f306f6154c8c2',
    messagingSenderId: '536029813863',
    projectId: 'talk-me-1879e',
    storageBucket: 'talk-me-1879e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOiTv2SOEkk9QokwU1ikzdIoiGP_Ao1Lc',
    appId: '1:536029813863:ios:345f2545b49d439654c8c2',
    messagingSenderId: '536029813863',
    projectId: 'talk-me-1879e',
    storageBucket: 'talk-me-1879e.firebasestorage.app',
    iosBundleId: 'com.example.talkMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOiTv2SOEkk9QokwU1ikzdIoiGP_Ao1Lc',
    appId: '1:536029813863:ios:345f2545b49d439654c8c2',
    messagingSenderId: '536029813863',
    projectId: 'talk-me-1879e',
    storageBucket: 'talk-me-1879e.firebasestorage.app',
    iosBundleId: 'com.example.talkMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3f9S-2jdQBKJSWXRL36eEzGG0Nvsx0tM',
    appId: '1:536029813863:web:42a0bb56cea4b69254c8c2',
    messagingSenderId: '536029813863',
    projectId: 'talk-me-1879e',
    authDomain: 'talk-me-1879e.firebaseapp.com',
    storageBucket: 'talk-me-1879e.firebasestorage.app',
    measurementId: 'G-SDP8QC7TYT',
  );
}
